### ISSUE TITLE
System Component for cookies

### ISSUE THREAD

**Issue by bobdesaunois** [bobdesaunois/emmaphp#67]
A system component for cookie control

**Comment by NathanBastiaans** [comment]
Testing this in GhostCMS.

**Comment by bobdesaunois** [comment]
Sweeeeeet

**Comment by bobdesaunois** [comment]
![huillie](https://cloud.githubusercontent.com/assets/6050628/11533865/2d686488-990c-11e5-82c5-aac5a9cadd91.gif)

**Comment by NathanBastiaans** [comment]
No fret, no sweat. dis shit works yo!
