### ISSUE TITLE
New way to throw errors in missing methods/controllers

### ISSUE THREAD

**Issue by bobdesaunois** [bobdesaunois/emmaphp#70]
The way it's done now is the application comes to a full stop and displays a message similar to something like "The controller could not be found".
Or method in the case of a method.

Perhaps there should be a more elegant way of crashing.
Or maybe not crashing at all and defaulting to the default controller?

An interesting matter.

**Comment by bobdesaunois** [comment]
I think I'll do something where you can configure this into all possible solutions

**Comment by jacted** [comment]
What about making it go to 404 page, and if debug mode is on show error message? @bobdesaunois

**Comment by bobdesaunois** [comment]
@jacted that sounds good I like that, I'll consider this when I'll start working on this.

**Comment by bobdesaunois** [comment]
Implemented in 0a54ce33a9bfbe2e6e771dbd53a188efc0fd0b79 by @jacted
