### ISSUE TITLE
Unify all config files

### ISSUE THREAD

**Issue by NathanBastiaans** [bobdesaunois/emmaphp#83]
all these config files.. why can't we just have one config file...

**Comment by bobdesaunois** [comment]
Honestly think this is a great idea and I never actually thought how bloated the config folder is with all these files.

**Comment by bobdesaunois** [comment]
Still I believe we should keep the mechanic that reads all config files in the config folder so users may actually create their own config files instead of having to rely on the config files that are already in place
.

**Comment by NathanBastiaans** [comment]
been there. done that!
