### ISSUE TITLE
Cookies should automatically adapt to HTTPS

### ISSUE THREAD

**Issue by bobdesaunois** [bobdesaunois/emmaphp#91]
When the framework is accessed through a secure HTTPS connection it should automatically set the `secure` boolean to `true`

**Comment by NathanBastiaans** [comment]
```
return ( ! empty ( $_SERVER['HTTPS'] ) && $_SERVER['HTTPS'] !== 'off' ) || $_SERVER['SERVER_PORT'] == 443;
```

This should return true on HTTPS although it does not 'guarantee' it. 
For example port 443 is the default https port but you 'could' change that of course (but only weird and/or retarded people do that I guess).

**Comment by bobdesaunois** [comment]
![da](https://cloud.githubusercontent.com/assets/6050628/12229960/c72d14ba-b84c-11e5-8d45-f5d6fe052648.jpg)

**Comment by NathanBastiaans** [comment]
haha gedaan in 8c633d3b244503b39d0e6b599c4584e05a1bbdef
